// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'header': string;
  'headeritem': string;
  'playbar': string;
  'sidebar': string;
}
export const cssExports: CssExports;
export default cssExports;
